version: '3'
services:
  dante:
    container_name: dante
    build: 
      context: ./dante
      args:
        username: ${DANTE_USER}
        password: ${DANTE_PASSWORD}
    ports:
      - "${DANTE_PORT}:1080"
    volumes:
      - ./dante/sockd.conf:/etc/sockd.conf
    restart: always

  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    ports:
      - "${MTPROTO_PORT}:443" 
    restart: always
    environment:
      - SECRET=${MTPROTO_SECRET}
      - SECRET_COUNT=1
      - WORKERS=2