version: '3'
services:

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${DATABASES}
      - POSTGRES_USER=u_nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    container_name: nextcloud
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=user_nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
    depends_on:
      - db
  
  web:
    image: nginx:alpine
    restart: always
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ${WEB_VOLUME}:/var/www/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud
      - gitea
      - transmission

  gitea:
    image: gitea/gitea:latest
    restart: always
    container_name: gitea
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:222:22"
    volumes:
      - ../gitea:/data
    environment:
      - ROOT_URL="http://127.0.0.1:8080/gitea/"
      - USER_UID=1000
      - USER_GID=1000
      - DISABLE_REGISTRATION=true
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${DATABASE_PASSWORD}
    depends_on:
      - db
    
  transmission:
    image: dperson/transmission:latest
    container_name: transmission
    ports:
      - 127.0.0.1:9091:9091/tcp
      - 51400:51413/tcp
      - 51400:51413/udp
    volumes:
      - ../media/config:/config
      - ../media/downloads:/downloads
      - ../media/torrent:/watch
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Moscow
      - TRUSER=${TORRENT_USER}
      - TRPASSWD=${TORRENT_PASSWORD}

  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn:latest
    container_name: openvpn
    ports:
     - "${OPENVPN_PORT}:1194/udp"
    restart: always
    volumes:
     - ${OPENVPN_DATA}:/etc/openvpn:rw

  dante:
    container_name: dante
    build: 
      context: ./dante
      args:
        username: ${DANTE_USER}
        password: ${DANTE_PASSWORD}
    ports:
      - "${DANTE_PORT}:1080"
    volumes:
      - ./dante/sockd.conf:/etc/sockd.conf:ro
    restart: always

  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    ports:
      - "${MTPROTO_PORT}:443" 
    restart: always
    environment:
      - SECRET=${MTPROTO_SECRET}
      - SECRET_COUNT=1
      - WORKERS=2
