version: '3'
services:

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${DATABASES}
      - POSTGRES_USER=u_nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  nextcloud:
    image: nextcloud
    restart: always
    container_name: nextcloud
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=user_nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
    labels:
      - "traefik.enabled=true"
      - "traefik.frontend=nextcloud"
      - "traefik.frontend.redirect.regex=^(.*)/nextcloud$$"
      - "traefik.frontend.redirect.replacement=$$1/nextcloud/"
      - "traefik.frontend.rule=PathPrefix: /nextcloud; ReplacePathRegex: ^/nextcloud/(.*) /$$1"
    depends_on:
      - db
  
  traefik:
    image: traefik
    command: --docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml

  gitea:
    image: gitea/gitea:latest
    restart: always
    container_name: gitea
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:222:22"
    volumes:
      - ${GIT_DATA}:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${DATABASE_PASSWORD}
    labels:
      - "traefik.enabled=true"
      - "traefik.frontend=nextcloud"
      - "traefik.frontend.redirect.regex=^(.*)/gitea$$"
      - "traefik.frontend.redirect.replacement=$$1/gitea/"
      - "traefik.frontend.rule=PathPrefix: /gitea; ReplacePathRegex: ^/gitea/(.*) /$$1"
      - "traefik.port=3000"
      - "traefik.protocol=http"

    depends_on:
      - db

  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn:latest
    container_name: openvpn
    ports:
     - "${OPENVPN_PORT}:1194/udp"
    restart: always
    volumes:
     - ${OPENVPN_DATA}:/etc/openvpn:rw

  dante:
    container_name: dante
    build: 
      context: ./dante
      args:
        username: ${DANTE_USER}
        password: ${DANTE_PASSWORD}
    ports:
      - "${DANTE_PORT}:1080"
    volumes:
      - ./dante/sockd.conf:/etc/sockd.conf:ro
    restart: always

  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    ports:
      - "${MTPROTO_PORT}:443" 
    restart: always
    environment:
      - SECRET=${MTPROTO_SECRET}
      - SECRET_COUNT=1
      - WORKERS=2