version: '3'
services:

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${DATABASES}
      - POSTGRES_USER=u_nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    container_name: nextcloud
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=user_nextcloud
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
    depends_on:
      - db
  
  web:
    image: nginx:alpine
    restart: always
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ${WEB_VOLUME}:/var/www/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud
      - transmission

  transmission:
    image: dperson/transmission:latest
    container_name: transmission
    ports:
      - 127.0.0.1:9091:9091/tcp
      - 51400:51413/tcp
      - 51400:51413/udp
    volumes:
      - ${TORRENT_CONFIG}:/var/lib/transmission-daemon/info
      - ${MEDIA_DATA}:/var/lib/transmission-daemon/Downloads
      - ${TORRENT_WATCH}:/var/lib/transmission-daemon/incomplete
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Moscow
      - TRUSER=${TORRENT_USER}
      - TRPASSWD=${TORRENT_PASSWORD}

  plex:
    container_name: plex
    hostname: plex
    image: plexinc/pms-docker:latest
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Moscow
      - ADVERTISE_IP=http://${SERVER_IP}:32400/
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - ${MEDIA_CONFIG}:/config
      - ${MEDIA_TMP}:/transcode
      - ${MEDIA_DATA}:/Media
